#!/bin/sh

## A simple shell script used to merge braches of Subversion.
temp_dir="/tmp/svn-merge-result"
versions=`svn log $2 --stop-on-copy | awk '/^r[0-9]*/ { print $1 }'`
head_version=`echo $versions | head -n 1 | grep -o '[0-9]*$'`
tail_version=`echo $versions | tail -n 1 | grep -o '[0-9]*$'`
merge_cmd="svn merge -r $tail_version:$head_version $2 ."
 
echo 'Preparing environment:'
rm -rf "${temp_dir}" && mkdir "${temp_dir}" && cd "${temp_dir}"
echo "Preparing environment done!\nChecking out $1"
svn co $1 .
echo "Checking out $1 done!\nMerging branches:$merge_cmd"
$merge_cmd
echo "Merging branches done:$merge_cmd"